portainer: 
  url: "http://example.lan/"
  interval: "" # uses cron syntax

containers:

  - name: "sonarr"
    portainer:
      webhook: "http://portainer.lan/api/webhooks/abcd12345" # webhook url from portainer
    container:
      url: "http://sonarr.lan" # base url for sonarr
      apiKey: "sonarrapikey"

  - name: "radarr"
    portainer:
      webhook: "http://portainer.lan/api/webhooks/abcd12345" # webhook url from portainer
    container:
      url: "http://radarr.lan" # base url for sonarr
      apiKey: "radarrapikey"
      
  