name: Upload Dockerhub Description

on:
  push:
    branches: ["main"]

jobs:
  update_dockerhub_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: anthonymolinari/container-updater
          short-description: Update containers with portainer webhooks
          readme-filepath: ./docker.md