name: Run Dagger Pipeline

on:
  push:
    branches: ['main'] 

jobs:
  dagger:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: install pipeline deps
        run: pip install -r ./dagger/requirements.txt

      - name: Execute pipeline
        run: python ./dagger/pipeline.py
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

                