name: Run Dagger Pipeline

on:
  push:
    branches: ['main'] 

jobs:
  dagger:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: install pipeline deps
        run: pip install -r ./dagger/requirements.txt

      - name: registry auth for dagger
        run: docker login -u ${{ secrects.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Execute pipeline
        run: python ./dagger/pipeline.py

      - name: registry logout
        run: docker logout
                